using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using QuanLyThuVien.BUS;
using QuanLyThuVien.DTO;

namespace QuanLyThuVien
{
    public partial class ucFrmQLSach : UserControl
    {
        Sach_BUS sachBUS = new Sach_BUS();
        public ucFrmQLSach()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            lb_MDG.Visible = false;
            lb_Trung.Visible = false;
            Sach _s = new Sach();
            Random rdm = new Random();
            _s.LanXuatBan= txtLanXuatBan.Text;
            _s.NamXuatBan = txtNamXuatBan.Text ;

            _s.KhoGiay = txtKhoGiay.Text;
            _s.SoTrang = txtSoTrang.Text;
            _s.cd =checkedHasCD.Checked ? 1 : 0;
      
            _s.MaSach = rdm.Next(0, 1000).ToString();
            _s.TenSach = txtTenSach.Text;
            _s.TacGia = txtTacGia.Text;
            _s.NhaXuatBan = txtNXB.Text;
            _s.TheLoai = txtNamXuatBan.Text;
            if (txtGiaSach.Text != "")
                _s.GiaSach = int.Parse(txtGiaSach.Text);
            _s.SoLuong = Convert.ToInt32(nb_SoLuong.Value);

            //kiem tra loi madocgia
            int check = sachBUS.Them(_s);
            if (check == 0)
                lb_MDG.Visible = true;
            else if (check == -1)
                lb_Trung.Visible = true;
            //load lai
            ucFrmQLSach_Load(sender, e);
            ResetGridview();
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {
            if (txtMaSach.Text != "")
            {
                sachBUS.Xoa(txtMaSach.Text);
                ResetGridview();
                ucFrmQLSach_Load(sender, e);
            }
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            lb_MDG.Visible = false;
            lb_Trung.Visible = false;
            Sach _s = new Sach();
            _s.MaSach = txtMaSach.Text;
            _s.TenSach = txtTenSach.Text;
            _s.TacGia = txtTacGia.Text;
            _s.NhaXuatBan = txtNXB.Text;
            _s.NamXuatBan = txtNamXuatBan.Text;
            _s.KhoGiay = txtKhoGiay.Text;
            _s.cd = checkedHasCD.Checked ? 1 : 0;
            if (txtGiaSach.Text != "")
                _s.GiaSach = int.Parse(txtGiaSach.Text);
         
            if (!sachBUS.Sua(_s))
                lb_MDG.Visible = true;
            ucFrmQLSach_Load(sender, e);
            ResetGridview();
        }
        private void ResetGridview()
        {
            txtMaSach.ResetText();
            txtTenSach.ResetText();
            txtNamXuatBan.ResetText();
            txtTacGia.ResetText();
            txtGiaSach.ResetText();
            txtNXB.ResetText();
            nb_SoLuong.ResetText();
            txtKhoGiay.ResetText();
            txtSoTrang.ResetText();
            txtLanXuatBan.ResetText();
            txtGiaSach.ResetText();


        }
        private void gridView1_CustomRowCellEditForEditing(object sender, DevExpress.XtraGrid.Views.Grid.CustomRowCellEditEventArgs e)
        {
            if (e.RowHandle >= 0)
            {
                txtMaSach.Text = gridView1.GetRowCellValue(e.RowHandle, "book_id").ToString();
                txtTenSach.Text = gridView1.GetRowCellValue(e.RowHandle, "book_title").ToString();
                txtLanXuatBan.Text = gridView1.GetRowCellValue(e.RowHandle, "publication_number").ToString();
                txtGiaSach.Text = gridView1.GetRowCellValue(e.RowHandle, "price").ToString();
                txtNXB.Text = gridView1.GetRowCellValue(e.RowHandle, "publisher").ToString();
                txtKhoGiay.Text = gridView1.GetRowCellValue(e.RowHandle, "paper_size").ToString();
                txtNamXuatBan.Text = gridView1.GetRowCellValue(e.RowHandle, "publication_year").ToString();
                txtSoTrang.Text = gridView1.GetRowCellValue(e.RowHandle, "page_count").ToString();

                if (gridView1.GetRowCellValue(e.RowHandle, "has_cd").Equals(true))
                {
                    checkedHasCD.Checked = true;
                }
                else
                {
                    checkedHasCD.Checked = false;
                }
            }
        }


        private void ucFrmQLSach_Load(object sender, EventArgs e)
        {
            // Thiết lập thuộc tính ReadOnly cho GridView

            gridView1.OptionsBehavior.Editable = true;

            gridControl1.DataSource = sachBUS.GetList();
        }

        private void txtTimSach_EditValueChanged(object sender, EventArgs e)
        {
            if (txtTimSach.Text == "")
            {
                gridControl1.DataSource = sachBUS.GetList();
            }
            else
                gridControl1.DataSource = sachBUS.TimKiem(txtTimSach.Text, "MaSach");
                
        }

        private void btnTimSach_Click(object sender, EventArgs e)
        {

        }

        private void lb_Trung_Click(object sender, EventArgs e)
        {

        }

        private void lb_MDG_Click(object sender, EventArgs e)
        {

        }

        private void txtTenSach_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void labelControl11_Click(object sender, EventArgs e)
        {

        }

        private void labelControl10_Click(object sender, EventArgs e)
        {

        }

        private void labelControl12_Click(object sender, EventArgs e)
        {

        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panelControl2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
                    }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void txtLanXuatBan_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}
